import {StyleSheet, Dimensions} from 'react-native';

export const styles = StyleSheet.create({
  headerContainer: {marginTop: '2%', alignSelf: 'center'},
  largeHeaderText: {
    fontFamily: 'Times New Roman',
    fontSize: 45,
    textTransform: 'uppercase',
  },
  smallHeaderText: {
    fontFamily: 'Arial',
    fontSize: 32,
    paddingLeft: 45,
    letterSpacing: 2,
  },
  loginDescription: {fontFamily: 'Arial', padding: 20, fontSize: 16},
  loginLibraryLink: {
    fontFamily: 'Arial',
    alignSelf: 'center',
    color: 'blue',
    marginBottom: 10,
  },
  loginContainer: {
    flex: 1,
  },
  loginForm: {
    alignItems: 'center',
    margin: 0,
  },
  loginTitle: {
    fontSize: 28,
    fontWeight: 'bold',
  },
  loginImage: {
    position: 'absolute',
    top: '15%',
    left: '5%',
    zIndex: -1,
    opacity: 0.5,
  },
  errorMessage: {
    color: 'red',
    backgroundColor: 'white',
    fontSize: 16,
    padding: 12,
    fontWeight: 'bold',
  },
  input: {
    width: 250,
    fontSize: 24,
    height: 58,
    padding: 10,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: 5,
    backgroundColor: 'white',
  },
  loginButton: {
    width: 250,
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    backgroundColor: '#212121',
  },
  loginText: {
    fontSize: 19,
    fontWeight: 'bold',
    color: '#fff',
  },
  logoutButton: {
    width: '45%',
    padding: 10,
    borderRadius: 10,
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#212121',
    position: 'absolute',
    bottom: 10,
    left: '5%',
  },
  logoutText: {
    fontSize: 19,
    fontWeight: 'bold',
    color: '#fff',
  },
  libraryCardContainer: {
    height: '100%',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  rotatedContainer: {
    transform: [{rotate: '90deg'}],
    height: Dimensions.get('window').width * 0.99,
    width: Dimensions.get('window').height * 0.9,
    justifyContent: 'center',
  },
  libraryCard: {
    marginBottom: '20%',
  },
  libraryCardDescription: {
    fontFamily: 'Arial',
    width: '55%',
    position: 'absolute',
    padding: 25,
    paddingLeft: 35,
    top: '45%',
  },
  imageContainer: {
    position: 'absolute',
    bottom: 0,
    left: -150,
    right: 0,
    top: '55%',
    zIndex: -1,
  },
  libraryCardImage: {
    alignSelf: 'center',
    height: '75%',
  },
  holderName: {
    textAlign: 'center',
    fontSize: 18,
  },
});
